(define (sum-of-squares x y) 
  (+ (* x x) (* y y)))
(define (larger x y)
  (cond ((> x y) x)
		(else y))
)
(define (sum-of-larger-squares x y z)
  (sum-of-squares 
	(larger x y)
	(cond ((> x y)
		   (larger y z))
		  (else (larger x z))
  	)
  )
)
